### PR TITLE
Add tests for transitive member access

### PR DESCRIPTION
**Pull request by craigthelinguist**
Test for accessing members of a module transitively in a way which circumvents authority

### CODE REVIEW

**Comment by craigthelinguist** [comment]
The tests fail halfway through because the current implementation cannot handle var declarations at the top-level of modules. The relevant part in wyvern.target.corewyvernIL.support.GenUtil.java is lines 88-89:

```java
else if (ast instanceof VarDeclaration) {
				throw new RuntimeException("top-level vars not implemented (are they implementable with this design?)");
```

This is part of the compile-time transformation of modules into objects, right? Are there plans to allow for top-level vars in these? What's the issue with top-level vars?

**Comment by JonathanAldrich** [comment]
The issue is that the current approach to translating a module means creating a series of let statements (so the statements execute in the right order, and so dependencies between them are supported) and then grouping all the module-level declarations into an object so that external clients can see them.  The problem is for "var" declarations the "var" created in the let statement can't be put in the outer "module" object, because a var created there won't share state with the var created earlier in the let.

There should be a solution to this--one example would be redirecting reads and writes to variables through internally generated getters and setters--but the module generation code is a bit messy (and buggy) and I think it'll be easier to solve this problem once we clean that up.

**Comment by JonathanAldrich** [comment]
I'm happy to merge the PR though, it's a nice test case.

**Comment by craigthelinguist** [comment]
With commit 03ed3611671dbd27d22df966c2d2855eb35d4ae would it be worth tackling top-level vars?

**Comment by JonathanAldrich** [comment]
Sure.  What I was thinking is:

 * Where we generate reads and writes to var fields now, instead generate calls to getters and setters named after the field.
 * Where we generate var fields, also generate a getter and setter for them, named appropriately (e.g. for a field "var name:String", generate getName():String/setName(s:String):String)

Does that make sense?

**Comment by craigthelinguist** [comment]
Sweet as, I'll give it a go.

**Comment by potanin** [comment]
Jonathan - does this mean that all vars should become getters and setters everywhere so in IL there are no vars?

**Comment by JonathanAldrich** [comment]
Well, in Wyvern vars are the only source of mutable state, and it's not possible to (locally and/or efficiently) simulate mutable state without a mutable state primitive (the best general simulation would pass around a map implemented as an immutable balanced binary tree to model state and therefore would incur a log n overhead for a data structure of size n).  So the translation will have to still have a var...it's just that all accesses to it will be redirected to getters and setters, and the implementations of the getter and setter methods are the only things that use the var directly after the translation.

Does this make sense?

**Pull request merged**
