### PR TITLE
Deadcode

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
Cleaning up some of the dead code. I've got a lot more to do!

### CODE REVIEW

**Comment by JonathanAldrich** [comment]
Yay, goodbye dead code!

But Travis CI has a build error--can you fix it before we merge?

**Comment by RobbieMcKinstry** [comment]
Yeah! I think I accidently deleted the code that generates `TypeParser.java`. Everything runs fine locally, which is why I pushed, but the source code doesn't get regenerated on Travis.

**Comment by JonathanAldrich** [comment]
"ant clean" followed by "ant test" is a way to avoid that.  But yeah, I've made that mistake too.

It looks like TypeParser comes from Wyvern.x (and various pieces of build.xml).  I wonder if you can get away with cutting the dependencies to it, rather than adding it back in?

**Comment by RobbieMcKinstry** [comment]
Woo! The tests pass!
I'm going to rebase this before we merge! I have a lot of dirty commits due to those Travis failures.

**Comment by RobbieMcKinstry** [comment]
Okay! It should be ready for a merge now!

**Pull request merged**
