### PR TITLE
Backend: Modules and FFI support

### PR DESCRIPTION
**Pull request by hcnelson99**
I would appreciate some feedback on this patch to make sure I'm going about things the right way. It isn't 100% polished.

Modules were implemented by adding an emitBytecode() method to ModuleResolver which uses the existing dependency handling code (ModuleResolver.sortDependencies) to spit out the list of module dependencies in the proper order. Bytecode is generated for each module and it's all packed into a single .wyb. On the javascript side, each module is just compiled into a javascript object and all of these object definitions are dumped into one .js file which runs like normal.

FFI is handled by generating CommonJS require() statements. I generate code which looks at the WYVERN_HOME environment variable to find .js files in the stdlib. Since WYVERN_HOME must be in the environment when you invoke node, it should be set in the user's .bashrc (it might not be set there if you rely on bin/wyvern to set it). We can't yet load npm libs or non-stdlib js files but that's easy to add. 

The biggest shortcoming of this patch is that I added a global static variable to BytecodeCompiler: javascriptFFIImports. It holds the javascript FFI imports for the current invocation of the bytecode compiler. It is only written in one place (FFI.doJavaScriptImport) and read in one place (ModuleResolver.emitBytecode) so it's not that evil of a global but I'd like to get rid of it. The problem is that these two functions are very far apart in the call stack and there doesn't seem to be any obvious way to get this data from one to the other without a global. The other option is storing the import data in the CoreWyvernIL ast and writing a visitor to gather it, but that seems like overkill and it would be slow + less clear. Is there a better way to do this? I tend to be more okay with globals than most people so let me know your thoughts.

Since I'm mostly looking for feedback, this patch has some shortcomings and maybe isn't ready for a merge:
* The javascript being FFIed into must have name mangled symbols. This is a little annoying to fix but not that bad. The backend just needs to deduce and propagate around the information about what are FFI objects so methods on them don't get mangled.
* The generated bytecode is specific to javascript. I wanted to get javascript working before I tried to generalize to make the generated bytecode platform-agnostic. This shouldn't be too bad to fix. I'd like PLATFORM_JAVASCRIPT to go away and become PLATFORM_BYTECODE.
* I haven't tested wyt files. They likely don't work (or they might since no javascript needs to be generated for them anyways)

### CODE REVIEW

**Comment by JonathanAldrich** [comment]
Some quick feedback (I have spotty internet so doing this via the email to
GitHub gateway).

emitBytecode(): this seems fine.  I assume this is for a particular module,
and results in emitting bytecode for all modules it depends on.

In the medium term it would be great to have some options here.  One
obvious option is one bytecode file per source file, and have the back end
be able to find, load, and compile them together.  Another option we will
probably want is to write bytecode just for a package tree (e.g. a
directory and all its subdirectories); anything used outside that package
can be referenced via import statements.  Finally, at some point we'll want
to support dynamically loading a module from bytecode.  None of this has to
be in the first back-end PR though.

The require approach in JavaScript sounds fine.  I don't like globals
either.  This is not a terrible use of them, but it might make the compiler
non-re-entrant, and I've tried (mostly successfully) to keep the compiler
reentrant.  Could you add the global information to the InterpreterState?
That's where "global" information is currently, and an InterpreterState is
available almost anywhere.  There's even a hack to get the current
InterpreterState, use InterpreterState.getLocalThreadInterpreter().  This
method uses Java's ThreadLocal library, preserving most cases of
re-entrancy.

How can the backend "deduce and propagate around the information about what
are FFI objects"?  An FFI object might be hidden under a Wyvern type and
get passed around arbitrarily, at least according to the current design of
the language and the Java/Pythong back ends.

I agree about PLATFORM_BYTECODE.  And .wyt shouldn't be too hard to add.

**Comment by hcnelson99** [comment]
> How can the backend "deduce and propagate around the information about what are FFI objects"? An FFI object might be hidden under a Wyvern type and get passed around arbitrarily, at least according to the current design of the language and the Java/Pythong back ends.

You're totally right about this one. How should I handle the fact that normally all identifiers are mangled (to make everything a legal javascript identifier) but FFI method calls cannot be mangled or else they won't resolve since presumably the javascript code we're FFIing into isn't mangled? I could envision doing something at runtime to handle this (javascript gives us the flexibility) but I would prefer not to. However, I can't really see how to handle this statically, especially given that we may load modules at runtime.

**Comment by JonathanAldrich** [comment]
> You're totally right about this one. How should I handle the fact that normally all identifiers are mangled (to make everything a legal javascript identifier) but FFI method calls cannot be mangled or else they won't resolve since presumably the javascript code we're FFIing into isn't mangled? I could envision doing something at runtime to handle this (javascript gives us the flexibility) but I would prefer not to. However, I can't really see how to handle this statically, especially given that we may load modules at runtime.

Hmm, the first thing that occurs to me, which I think the python backend might already be doing -- can the name mangling be the identity function on all names that are already legal javascript identifiers?

Then you only do something special when we use something in Wyvern that isn't legal JavaScript, but by definition those things can't be imported things.

Jonathan

**Comment by potanin** [comment]
We had an interesting discussion just now on the two issues:

1. Interfacing between different languages in a consistent manner, including (likely) interface generation on each end to make these names match up “by definition”. This will help with JS problem below in the backend and make some of the Java interop (calling Wyvern objects from Java in particular) easier.

2. Standardising stdlib for both primitives and common objects like stdout - treating them in a common statically resolvable way and ideally making a prelude that can rely on stdlib only. :)

Henry will expand on both shortly I hope and (1) should help solve the below issues.

Cheers,
Alex.

**Pull request closed without merging**
